base: /vue-press-blog/
title: Mybrc91's Site
description: Just A Tech Site.
head:
  - - link
    - rel: icon
      href: /favicon.png
serviceWorker: true
themeConfig:
  nav:
    - text: Blog
      link: /blog/
  sidebar:
    /blog/:
      - Deploy-Vuepress-Blog-On-TravisCI
      - deploy-gogs-on-raspberrypi
      - wrap-viewpager
